# Generated by Django 4.2.1 on 2023-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_turn_time_alter_turn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='time',
            field=models.CharField(choices=[('14:00 - 16:00', '14:00 - 16:00'), ('08:00 - 10:00', '08:00 - 10:00'), ('18:00 - 20:00', '18:00 - 20:00'), ('12:00 - 14:00', '12:00 - 14:00'), ('16:00 - 18:00', '16:00 - 18:00'), ('10:00 - 12:00', '10:00 - 12:00')]),
        ),
    ]
