# Generated by Django 4.2.1 on 2023-05-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(2, '2'), (5, '5'), (3, '3'), (4, '4'), (1, '1')])),
                ('comment', models.CharField(max_length=500)),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turn.turn')),
            ],
        ),
    ]
