# Generated by Django 4.2.1 on 2023-06-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0002_alter_qualify_comment_alter_qualify_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualify',
            name='rate',
            field=models.IntegerField(choices=[(4, '4'), (5, '5'), (1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
