# Generated by Django 4.2.1 on 2023-06-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_alter_qualify_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualify',
            name='rate',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (1, '1'), (2, '2')]),
        ),
    ]
