# Generated by Django 4.2.1 on 2023-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0004_alter_qualify_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualify',
            name='rate',
            field=models.IntegerField(choices=[(4, '4'), (1, '1'), (2, '2'), (5, '5'), (3, '3')]),
        ),
    ]
